# Generated by Django 3.1.7 on 2021-07-21 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0007_auto_20210719_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Editable_Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_profit', models.IntegerField(default=0.0)),
                ('closed_tradePL', models.IntegerField(default=0.0)),
                ('deposite_withdrawal', models.IntegerField(default=0.0)),
                ('balance', models.IntegerField(default=0.0)),
                ('total_credit_faculty', models.IntegerField(default=0.0)),
                ('equity', models.IntegerField(default=0.0)),
                ('margin_Requirement', models.IntegerField(default=0.0)),
                ('available_margin', models.IntegerField(default=0.0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
