# Generated by Django 3.1.7 on 2021-07-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0008_user_editable_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_editable_balance',
            options={'verbose_name': 'User Editable Balance'},
        ),
        migrations.AddField(
            model_name='user_editable_balance',
            name='ac_summary',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='user_editable_balance',
            name='estimated_24gr_revenue',
            field=models.IntegerField(default=0.0),
        ),
    ]
