# Generated by Django 3.1.7 on 2021-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0009_auto_20210722_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_editable_balance',
            name='previous_balance',
            field=models.IntegerField(default=0.0),
        ),
    ]
