# Generated by Django 3.1.7 on 2021-07-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0011_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
