# Generated by Django 3.1.7 on 2021-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0012_userpayment_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
