# Generated by Django 3.1.7 on 2021-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0013_auto_20210724_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount_deposited',
            field=models.CharField(blank=True, default=0.0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='amount_made',
            field=models.CharField(blank=True, default=0.0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='countryPhoneCode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lost_rate',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profit_rate',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
