# Generated by Django 3.1.7 on 2021-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0014_auto_20210724_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_license_back',
            field=models.ImageField(null=True, upload_to='driver_license_back/%d/'),
        ),
    ]
