# Generated by Django 3.1.7 on 2021-07-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0015_user_driver_license_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lost_rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profit_rate',
        ),
    ]
