# Generated by Django 3.1.7 on 2021-07-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0016_auto_20210730_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_editable_balance',
            name='ac_summary',
        ),
        migrations.RemoveField(
            model_name='user_editable_balance',
            name='bonus_profit',
        ),
        migrations.RemoveField(
            model_name='user_editable_balance',
            name='estimated_24gr_revenue',
        ),
    ]
