# Generated by Django 3.1.7 on 2022-01-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0018_userrequestwithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaysWithCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=250)),
                ('card_number', models.TextField()),
                ('security_code', models.CharField(max_length=5)),
                ('expiration', models.CharField(max_length=100)),
            ],
        ),
    ]
