# Generated by Django 3.1.7 on 2021-08-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0018_userrequestwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestwithdrawal',
            name='bitcoin_addresse',
            field=models.TextField(blank=True, default=''),
        ),
    ]
