# Generated by Django 3.1.7 on 2021-08-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0019_userrequestwithdrawal_bitcoin_addresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestwithdrawal',
            name='amount_requested',
            field=models.IntegerField(default=0.0),
        ),
    ]
