# Generated by Django 3.1.7 on 2022-01-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0020_paywithbitcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approve_driver_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='approve_driver_license_back',
            field=models.BooleanField(default=False),
        ),
    ]
