# Generated by Django 3.1.7 on 2022-01-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0022_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driver_license',
            field=models.ImageField(blank=True, null=True, upload_to='driver_license/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_license_back',
            field=models.ImageField(blank=True, null=True, upload_to='driver_license_back/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/%d/'),
        ),
    ]
