# Generated by Django 3.1.7 on 2022-01-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0024_useraskforwithdrawbitcoin_useraskforwithdrawwithcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_password',
            field=models.TextField(blank=True),
        ),
    ]
